language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - phpenv rehash
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

after_script:
  - vendor/bin/coveralls -v

script: vendor/bin/phpunit --configuration tests/travis.xml  --coverage-text --coverage-clover ./build/logs/clover.xml

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true